org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false

systemProp.net.minecraftforge.gradle.repo.recompile.fork=true
systemProp.net.minecraftforge.gradle.repo.recompile.fork.args=-Xmx5G

systemProp.net.minecraftforge.gradle.repo.attach=false

minecraft_version=1.21.7
minecraft_version_range=[1.21.7,1.22)
forge_version=57.0.2
forge_version_range=[0,)
loader_version_range=[0,)

mapping_channel=official
mapping_version=1.21.7

mod_id=squakeported
mod_name=Squake Ported
mod_license=All Rights Reserved
mod_version=1_13
mod_group_id=mett.palemannie.squakeported
mod_authors=Pale Mannie, Manfred Blasser
mod_description=A Quake-style movement mod for Minecraft